### PR TITLE
Feature/variable inclusion

### PR DESCRIPTION
**Pull request by CarolinaVelasco**
Selected variables relevant to housing quality. Included R script that creates a csv file with the description of the variables of interest.

### CODE REVIEW

**Comment by jcochanc** [comment]
@CarolinaVelasco, this looks great. I see no reason not to continue.

**Review by jcochanc — APPROVED** [review]
Ready to go!

**Review by lindechen — APPROVED** [review]
Looks good to me!

**Comment by CarolinaVelasco** [comment]
This solves #4

**Pull request merged**
